tutorial/acetutors/urls.py
from django.conf.urls import url
from . import views

app_name = 'acetutors'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<info_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^create_albums/$', views.create_album, name='create_album'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profiletutor/$', views.profiletutor, name='profiletutor'),
    url(r'^(?P<info_id>[0-9]+)/create_note/$', views.create_song, name='create_song'),
    url(r'^(?P<info_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^(?P<info_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<info_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^tutee/$', views.tutee, name='tutee'),
    url(r'tutor/$', views.tutor, name='tutor'),

]

tutorial/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tutorial/', include('acetutors.urls')),
    url(r'^', include('acetutors.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/acetutors/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Information1(models.Model):
    user = models.ForeignKey(User, default=1)
    full_name = models.CharField(max_length=250)
    email = models.CharField(max_length=500)
    course = models.CharField(max_length=100)
    picture_topic = models.FileField()
    is_favorite = models.BooleanField(default=False)
    tutorial_date = models.DateField()
    tutorial_start = models.TimeField()
    tutorial_end = models.TimeField()

    def __str__(self):
        return self.email + ' - ' + self.full_name


class Song(models.Model):
    info = models.ForeignKey(Information1, on_delete=models.CASCADE)
    info_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.info_title


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    type = models.CharField(max_length=250)
    contact_number = models.CharField(max_length=250)

    def __str__(self):
        return self.user.username


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.CharField(max_length=200)

    def __str__(self):
        return self.name

tutorial/acetutors/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Information1, Song, UserProfileInfo


your_course = [
    ('', '--------------------'),
    ('algebra', 'College Algebra'),
    ('integral', 'Integral Calculus'),
    ('diffcal', 'Differential Calculus'),
    ('differential ', 'Differentail Equation'),
    ]


types = [
    ('', '--------------------------------'),
    ('tutor', 'Tutor'),
    ('tutee', 'Tutee')
]


class DetailForm(forms.ModelForm):
    course = forms.CharField(widget=forms.Select(choices=your_course))

    class Meta:
        model = Information1
        fields = ['full_name', 'email', 'course', 'picture_topic', 'tutorial_date', 'tutorial_start', 'tutorial_end']
        widgets = {
            'tutorial_date': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD', 'id': "tutorial_date"}),
            'tutorial_start': forms.TimeInput(attrs={'placeholder': 'HH:MM', 'id': "tutorial_start"}),
            'tutorial_end': forms.TimeInput(attrs={'placeholder': 'HH:MM', 'id': "tutorial_end"}),
        }


class InfoForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['info_title', 'files_here']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


class UserProfileInfoForm(forms.ModelForm):
    type = forms.CharField(widget=forms.Select(choices=types))

    class Meta:
        model = UserProfileInfo
        fields = ['type', 'contact_number']

tutorial/acetutors/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.db.models import Q
from django.contrib import messages
from acetutors.forms import DetailForm, InfoForm, UserForm, UserProfileInfoForm
from acetutors.models import User, Information1, Song, UserProfileInfo, Feedback

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg', 'gif']


def tutee(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        userprofileinfo = UserProfileInfo.objects.all()

        print(userprofileinfo)

        if user is not None:
            if user.is_active:
                print(type)
                login(request, user)
                u = User.objects.get(username=username)
                request.session['user_id'] = u.id
                request.session['user_username'] = u.username
                albums = Information1.objects.filter(user=request.user)
                t = UserProfileInfo.objects.get(id=u.id)
                if t.type == "tutee":
                    return render(request, 'webs/index.html', {'albums': albums})
                elif t.type == "tutor":
                    return render(request, 'webs/tutor_profile.html')
                # else:
                #     return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'webs/login.html', {'error_message': 'Invalid login'})
    return render(request, 'webs/login.html')


def tutor(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        userprofileinfo = UserProfileInfo.objects.all()
        if user is not None:
            if user.is_active and user.userprofile.type == "Tutor":
                login(request, user)
                u = User.objects.get(username=username)
                request.session['user_id'] = u.id
                request.session['user_username'] = u.username
                albums = UserProfileInfo.objects.filter(user=request.user)
            return render(request, 'webs/tutor_profile.html', {'albums': albums})

                # else:
                #     return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'webs/login_tutor.html', {'error_message': 'Invalid login'})
    return render(request, 'webs/login_tutor.html')


def create_album(request):
    # userinfo = User.objects.get(id=request.session['user_id'])
    # userprofileinfo = UserProfileInfo.objects.get(user_id=request.session['user_id'])
    if not request.user.is_authenticated():
        return render(request, 'webs/login.html')
    else:
        form = DetailForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.picture_topic = request.FILES['picture_topic']
            file_type = info.picture_topic.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'info': info,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'webs/create_album.html', context)
            info.save()
            return render(request, 'webs/detail.html', {'info': info})

        context = {
            "form": form,
        }
        return render(request, 'webs/create_album.html', context)

# Song is for Description


def create_song(request, info_id):
    form = InfoForm(request.POST or None, request.FILES or None)
    info = get_object_or_404(Information1, pk=info_id)
    if form.is_valid():
        infos_songs = info.song_set.all()
        for s in infos_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'info': info,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'webs/create_song.html', context)
        song = form.save(commit=False)
        song.info = info
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'info': info,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'webs/create_song.html', context)

        song.save()
        return render(request, 'webs/detail.html', {'info': info})
    context = {
        'info': info,
        'form': form,
    }
    return render(request, 'webs/create_song.html', context)

# album is for Schedule


def delete_album(request, info_id):
    info = Information1.objects.get(pk=info_id)
    info.delete()
    albums = Information1.objects.filter(user=request.user)
    return render(request, 'webs/index.html', {'albums': albums})


def delete_song(request, info_id, song_id):
    info = get_object_or_404(Information1, pk=info_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'webs/detail.html', {'info': info})


def detail(request, info_id):
    if not request.user.is_authenticated():
        return render(request, 'webs/login.html')
    else:
        user = request.user
        info = get_object_or_404(Information1, pk=info_id)
    return render(request, 'webs/detail.html', {'info': info, 'user': user})


def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_album(request, info_id):
    info = get_object_or_404(Information1, pk=info_id)
    try:
        if info.is_favorite:
            info.is_favorite = False
        else:
            info.is_favorite = True
        info.save()
    except (KeyError, Information1.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']

        feed = Feedback(name=name, email=email, message=message)
        feed.save()

    if not request.user.is_authenticated():
        return render(request, 'webs/new_homepage1.html')
    else:
        infos = Information1.objects.filter(user=request.user)
        song_results = Song.objects.all()
        query = request.GET.get("q")
        if query:
            infos = infos.filter(
                Q(email__icontains=query) |
                Q(full_name__icontains=query)
            ).distinct()
            song_results = song_results.filter(
                Q(song_title__icontains=query)
            ).distinct()
            return render(request, 'webs/index.html', {
                'infos': infos,
                'songs': song_results,
            })
        else:
            return render(request, 'webs/index.html', {'infos': infos})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'webs/new_homepage1.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        type = request.POST['type']
        user = authenticate(username=username, password=password, type=type)
        if user is not None:
            if user.is_active and type == 'Tutee':
                login(request, user)
                albums = Information1.objects.filter(user=request.user)
                return render(request, 'webs/index.html', {'albums': albums})
            elif user.is_active and type == 'Tutor':
                login(request, user)
                albums = UserProfileInfo.objects.filter(user=request.user)
                return render(request, 'webs/tutor_profile.html', {'albums': albums})
        else:
            return render(request, 'webs/login.html', {'error_message': 'Invalid login'})
    return render(request, 'webs/login.html')


def register(request):
    form = UserForm(request.POST or None)
    form1 = UserProfileInfoForm(request.POST or None)
    if form.is_valid() and form1.is_valid():
        user = form.save(commit=False)
        firstname = form.cleaned_data['first_name']
        lastname = form.cleaned_data['last_name']
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(firstname=firstname, lastname=lastname, username=username, password=password)
        userprofile = form1.save(commit=False)
        userprofile.user = user
        userprofile.save()
        if user is not None and profile is not None:
            if user.is_active:
                login(request, user)
                albums = Information1.objects.filter(user=request.user)
                return render(request, 'webs/login.html', {'albums': albums})
    context = {
        "form": form,

tutorial/acetutors/templates/webs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}A.C.E. Tutors{% endblock %}</title>
    {% load staticfiles %}
{#    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'music/styles.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'acetutors/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'acetutors:index' %}">A.C.E. Tutors</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'acetutors:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Tutorial</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'acetutors:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Schedule</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'acetutors:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'acetutors:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create Schedule
                    </a>
                </li>
                <li>
                    <a href="{% url 'acetutors:profile' %}">
                        <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>&nbsp; My Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'acetutors:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
        <script src="{% static 'music/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'music/jonthornton-jquery-timepicker/jonthornton-jquery-timepicker/jquery.timepicker.js' %}"></script>
        <link rel="stylesheet" href="{% static 'music/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
        <link rel="stylesheet" href="{% static 'music/jonthornton-jquery-timepicker/jonthornton-jquery-timepicker/jquery.timepicker.css' %}">
        <script src="{% static 'music/js/timeschedule.js' %}"></script>

</body>
</html>

tutorial/acetutors/templates/webs/detail.html
{% extends 'webs/base.html' %}
{% block title %}{{ info }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href= "tutorial/detail/{{ info.id }}">
                        {% if info.picture_topic %}
                            <img src="{{ info.picture_topic.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ info.info_title }} <small>{{ info.course }}</small></h1>
                    <h2>{{ info.full_name }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'acetutors:detail' info.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'acetutors:create_song' info.id %}">Add New Note</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Description</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Accept</th>
                            <th>Decline</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in info.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'acetutors:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'acetutors:delete_song' info.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

tutorial/acetutors/templates/webs/form_template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }} </div>
    </div>

{% endfor %}

tutorial/acetutors/templates/webs/index.html
{% extends 'webs/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <h3 style="color: white;">Welcome! {{ user.username }} </h3>
        </div>
        {% if infos %}
            {% for info in infos %}
                <div class="col-sm-6 col-lg-4">
                    <div class="thumbnail">
                        <a href="{% url 'acetutors:detail' info.id %}">
                            <img src="{{ info.picture_topic.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                         <h2><b>Name: </b>{{ info.full_name }}</h2>
                            <h4><b>Email: </b>{{ info.email }}</h4>
                            <h4><b>Course: </b>{{ info.course }}</h4>
                            <h4><b>Date: </b>{{ info.tutorial_date }}</h4>
                            <h4><b>Time: </b>{{ info.tutorial_start }} to {{ info.tutorial_end }} </h4>


                            <!-- View Details -->
                            <a href="{% url 'acetutors:detail' info.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'acetutors:delete_album' info.id %}"  method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="info_id" value="{{ info.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'acetutors:favorite_album' info.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if info.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'acetutors:create_album' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Create New Schedule
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Full Name</th>
                                    <th>Audio File</th>
                                    <th>Information</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.info_title }}</td>
                                        <td>{{ song.info.full_name }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'acetutors:detail' song.info.id %}">
                                                <img src="{{ song.info.picture_topic.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'acetutors:detail' song.info.id %}">{{ song.info.email }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'acetutors:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

tutorial/acetutors/templates/webs/songs.html
{% extends 'webs/base.html' %}
{% block title %}Description{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'acetutors:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'acetutors:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Description</th>
                                <th>Full Name</th>
                                <th>Audio File</th>
                                <th>Picture Topic / Email</th>
                                <th>Accepted</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.info_title }}</td>
                                    <td>{{ song.info.full_name }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'acetutors:detail' song.info.id %}">
                                            <img src="{{ song.info.picture_topic.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'acetutors:detail' song.info.id %}">{{ song.info.email }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'acetutors:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}